/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ekutt_example_gpacalculator_GPACalculator */

#ifndef _Included_ekutt_example_gpacalculator_GPACalculator
#define _Included_ekutt_example_gpacalculator_GPACalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ekutt_example_gpacalculator_GPACalculator
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ekutt_example_gpacalculator_GPACalculator_nativeCreateObject
  (JNIEnv *, jobject);

/*
 * Class:     ekutt_example_gpacalculator_GPACalculator
 * Method:    calculateGPAs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ekutt_example_gpacalculator_GPACalculator_calculateGPAs
  (JNIEnv *, jobject,jlong nativeObjectHandle);

/*
 * Class:     ekutt_example_gpacalculator_GPACalculator
 * Method:    addGrade
 * Signature: (Ljava/lang/String;FI)V
 */
JNIEXPORT void JNICALL Java_ekutt_example_gpacalculator_GPACalculator_addGrade
  (JNIEnv *, jobject, jlong nativeObjectHandle, jstring, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
